# Lecture 3 - Numpy for Data Analysis Home Learning

In [1]:
import numpy as np

**Task 1 - Create a 1D array of numbers from 0 to 9**

In [2]:
One_D=np.arange(10)
print(One_D)

[0 1 2 3 4 5 6 7 8 9]


**Task 2 - Create a 3×3 NumPy array of all Boolean value Trues**

In [117]:
Trues=np.ones((3,3),dtype=bool)
print(Trues)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Task 3 - Extract all odd numbers from array of 1 10**

In [23]:
array=np.arange(1,11)
array_odd=np.arange(1,11,2)
array_even=np.arange(2,11,2)
print("Original array: ", array)
print("Odd array: ",array_odd)
print("Even array: ",array_even)

Original array:  [ 1  2  3  4  5  6  7  8  9 10]
Odd array:  [1 3 5 7 9]
Even array:  [ 2  4  6  8 10]


**Task 4 - Replace all odd numbers in an array of 1 to 10 with the value -1**

In [79]:
array=np.arange(1,11)
print(array)
array2=(array%2==1)
array[array2]=-1
print(array)


[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


**Task 5 - Convert a 1D array to a 2D array with 2 rows**

In [41]:
One_D=np.arange(1,21)
Two_D=One_D.reshape(2,10)
print("1D Array: ", One_D)
print("2D Array: ")
print(Two_D)

1D Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D Array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


**Task 6 - Create two arrays a and b, stack these two arrays vertically use the
np.dot and np.sum to calculate totals**

In [76]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print("a = ", a)
print("b = ", b)

c=np.vstack((a,b)) #vertical stack
print("c = ", c)

sum=np.sum(c) #matrix sum
print("sum = ", sum)

d=np.dot(a,b) #matrix multiplication
print("d = ", d)



a =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
b =  [[10 11 12]
 [13 14 15]
 [16 17 18]]
c =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
sum =  171
d =  [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


# Extension

**Task 1 - Create the following pattern without hardcoding. 
Use only NumPy functions 
 array(1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3)**

In [101]:
a=np.arange(1,4)
print("a= ", a)

b=np.ones(3)
print("b= ", b)

c=b*2
print("c= ", c)

d=b*3
print("d= ", d)

e=np.hstack((b,c,d,a,a,a)) 
print("e = ", e)



a=  [1 2 3]
b=  [1. 1. 1.]
c=  [2. 2. 2.]
d=  [3. 3. 3.]
e =  [1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


**Task 2 - In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating
items present in array b**

In [112]:
a=np.arange(1,6)
b=np.arange(4,10)
c=np.hstack((a,b))
d=np.unique(c)

print("a= ", a)
print("b= ", b)

new_b=d[5:]
print("new b = ", new_b)


a=  [1 2 3 4 5]
b=  [4 5 6 7 8 9]
new b =  [6 7 8 9]


**Task 3 - Get all items between 5 and 10 from a and b and sum them together**

In [115]:
print("a= ", a)
print("b= ", b)
print("a+b = ", c)
print("items between 5 and 10 = ", new_b)
e=np.sum(new_b)
print("sum = ", e)

a=  [1 2 3 4 5]
b=  [4 5 6 7 8 9]
a+b =  [1 2 3 4 5 4 5 6 7 8 9]
items between 5 and 10 =  [6 7 8 9]
sum =  30
