In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(array[1:5])

[2 3 4 5]


In [3]:
zeros=np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
ones=np.ones(8)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
random=np.random.rand(3,4)
print(random)

[[0.78904286 0.67911866 0.13474738 0.33685397]
 [0.92157505 0.28618505 0.48518808 0.21428233]
 [0.93709428 0.08271883 0.9928376  0.38531211]]


In [6]:
eye=np.eye(6)
print(eye)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [7]:
even=np.arange(6)
print(even)

[0 1 2 3 4 5]


In [9]:
array=np.arange(0,15,2)
print(array)

[ 0  2  4  6  8 10 12 14]


In [10]:
array=np.arange(1,13)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
newArray=array.reshape(4,3)
print(newArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(len(array))

12


In [14]:
print("Original: ", array)
print("Subtract: ", array-10)
print("Multiply: ", array*10)
print("Divide: ", array/10)
print("Power: ", array**2)

Original:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Subtract:  [-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2]
Multiply:  [ 10  20  30  40  50  60  70  80  90 100 110 120]
Divide:  [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2]
Power:  [  1   4   9  16  25  36  49  64  81 100 121 144]


In [15]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.dot(a,b) #np.dot = matrix multiplication, only when column numbers match
print(a)
print(b)
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [16]:
sum=np.sum(c) #np.sum = overall sum of all teh elements in the array
print(sum)

1944


In [18]:
e=np.sum(c,axis=0) #overall sum of all elements in the array column
print(e)

[603 648 693]


In [19]:
e=np.sum(c,axis=1) #overall sum of all elements in the array row
print(e)

[ 270  648 1026]
